// Generated by scripts/sync-schema-index.ts — do not edit manually.
export * from "./audit";
export * from "./columns";
export * from "./leagues";
export * from "./players";
export * from "./teams";
export * from "./types";
export * from "./users";

/**
 * @example
 * import { pgTable, text } from "drizzle-orm/pg-core";
 * import {
 *   auditColumns,
 *   createAuditRelations,
 *   idColumn,
 *   type InferQueryModel,
 * } from "@repo/db/schema";
 *
 * export const posts = pgTable("posts", {
 *   ...idColumn,
 *   title: text("title").notNull(),
 *   ...auditColumns,
 * });
 *
 * export const postsRelations = createAuditRelations(posts, "posts");
 *
 * export type Post = InferQueryModel<
 *   "posts",
 *   { with: { creator: true; updater: true; deleter: true } }
 * >;
 */
