import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const schemaDir = path.resolve(scriptDir, "../src/schema");
const indexPath = path.join(schemaDir, "index.ts");

const schemaFiles = (await readdir(schemaDir))
  .filter((file) => file.endsWith(".ts") && file !== "index.ts")
  .sort();

const exports = schemaFiles
  .map((file) => `export * from "./${file.replace(/\.ts$/, "")}";`)
  .join("\n");

const example = `
/**
 * @example
 * import { pgTable, text } from "drizzle-orm/pg-core";
 * import {
 *   auditColumns,
 *   createAuditRelations,
 *   idColumn,
 *   type InferQueryModel,
 * } from "@repo/db/schema";
 *
 * export const posts = pgTable("posts", {
 *   ...idColumn,
 *   title: text("title").notNull(),
 *   ...auditColumns,
 * });
 *
 * export const postsRelations = createAuditRelations(posts, "posts");
 *
 * export type Post = InferQueryModel<
 *   "posts",
 *   { with: { creator: true; updater: true; deleter: true } }
 * >;
 */`;

const content = `// Generated by scripts/sync-schema-index.ts — do not edit manually.
${exports}
${example}
`;

await writeFile(indexPath, content);

console.log(
  `Synced schema index with ${schemaFiles.length} modules: ${schemaFiles.join(", ")}`,
);
